services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: rsr_srv_rsr
      DB_PORT: 3306
      DB_NAME: marketing
      DB_USER: rsr
      DB_PASS: N@v3gador
      EXTERNAL_API_KEY: rsr-externa-415749
